import{a as f,i as d,S as y}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function h(o,t){try{const r=new URLSearchParams({key:"47380921-4d10a9da0d1514e8969d771c8",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t});L();const a=await f.get(`https://pixabay.com/api/?${r}`),e=a.data.hits,s=a.data.totalHits,n=Math.ceil(s/15),l=t>=n;return(e.length<15||l)&&document.querySelector(".load-more").classList.add("hidden"),S(),{photosArr:e,isLastPage:l,totalPages:n}}catch{console.log("error"),document.querySelector(".load-more").classList.add("hidden"),d.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Something went wrong. Please try again later!"})}}const L=function(){const o=document.querySelector(".loaderMore");o.innerHTML='<span class="loader"></span>'},S=function(){document.querySelector(".load");const o=document.querySelector(".loaderMore");o.innerHTML=""},F=document.querySelector(".gallery"),P=o=>{const t=o.map(({largeImageURL:r,webformatURL:a,tags:e,likes:s,views:n,comments:l,downloads:m})=>`<li class='gallery-item'>
    <a class='gallery-link' href='${r}'>
    <img class='gallery-image' src='${a}' alt='${e}'/>
    </a>
    <div class='container-app'>
    <p><span>Likes</span> ${s}</p>
    <p><span>Views</span> ${n}</p>
    <p><span>Comments</span> ${l}</p>
    <p><span>Downloads</span> ${m}</p>
  </div>
   </li>`).join("");F.insertAdjacentHTML("beforeend",t)},u=document.querySelector("form"),w=document.querySelector(".gallery"),i=document.querySelector(".load-more");let p=1,c;i.addEventListener("click",b);u.addEventListener("submit",q);async function b(o){o.preventDefault(),i.disabled=!0;try{p+=1;const{photosArr:t,isLastPage:r}=await h(c,p);g(t,r)}catch(t){console.error(t.message)}i.disabled=!1,C()}async function q(o){if(o.preventDefault(),c=u.elements.search.value,i.classList.add("hidden"),w.innerHTML="",c===""){v();return}try{const{photosArr:t,isLastPage:r}=await h(c,p);g(t,r)}catch(t){console.error(t.message)}u.reset()}function g(o,t){const r=document.querySelector(".loader"),a=o;if(a.length===0){M(),i.classList.add("hidden"),r&&r.remove();return}P(a),t?(i.classList.add("hidden"),d.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("hidden"),r&&r.remove(),$()}function v(){d.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Please, enter what do you want to find!"})}function M(){d.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function $(){let o=new y(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});o.on("show.simpleLightbox"),o.refresh()}function C(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
