import{i as c,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m=n=>{const o=`https://pixabay.com/api/?${new URLSearchParams({key:"47380921-4d10a9da0d1514e8969d771c8",q:n,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(o).then(s=>{if(!s.ok)throw new Error(`HTTP error! Status: ${s.status}`);return s.json()})},d=document.querySelector(".gallery"),f=n=>{const r=n.map(({largeImageURL:o,webformatURL:s,tags:e,likes:t,views:a,comments:l,downloads:u})=>`<li class='gallery-item'>
    <a class='gallery-link' href='${o}'>
    <img class='gallery-image' src='${s}' alt='${e}'/>
    </a>
    <div class='container-app'>
    <p><span>Likes</span> ${t}</p>
    <p><span>Views</span> ${a}</p>
    <p><span>Comments</span> ${l}</p>
    <p><span>Downloads</span> ${u}</p>
  </div>
   </li>`).join("");d.innerHTML=r},i=document.querySelector("form"),h=document.querySelector(".gallery");i.addEventListener("submit",g);function g(n){n.preventDefault();const r=i.elements.search.value;if(r===""){L();return}i.insertAdjacentHTML("afterend",'<span class="loader"></span>'),h.innerHTML="",m(r).then(o=>y(o)).catch(o=>{console.error(o.message),document.querySelector(".loader").remove()}),i.reset()}function y(n){const r=document.querySelector(".loader"),o=n.hits;if(o.length===0){S(),r.remove();return}f(o),r.remove(),P(),i.reset()}function L(){c.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Please, enter what do you want to find!"})}function S(){c.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function P(){let n=new p(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});n.on("show.simpleLightbox"),n.refresh()}
//# sourceMappingURL=index.js.map
